// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykxpgbrgckmkxxpsxtnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlreHBnYnJnY2tta3h4cHN4dG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MTIwMjQsImV4cCI6MjA1MjA4ODAyNH0.4P-J9xaPHG7O2iYXodcL1mBWaUm2NCSMNnHk8eL0q7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);